### ISSUE TITLE
Selection of resolution-dependent scaling factors could be extended/refactored to cover external (non-NASA) grids

### ISSUE THREAD

**Issue by rmontuoro** [GEOS-ESM/GOCART#18] opened 2021-02-05 17:12 UTC
Resolution-dependent scaling factors used to modulate sea salt emissions are selected based on standard NASA cubic grid resolutions (C48, C90, C180, C360, C720). These resolutions are hardcoded in function `Chem_UtilResVal()`, included in the process library.

Since GOCART may now be driven using external grids (as in the case of UFS), the function above could be extended to include other global grids (_e.g._ NOAA C48, C96, C192, C384, C768, C1152, C3072) or refactored to use grid point distance rather than the number of grid point per tile to select the proper scaling coefficient.

**Comment by tclune** [comment] 2021-02-05 17:26
Hmm.  This is somewhat surprising - GEOS generally tries very hard to express everything in an resolution-independent manner.   I'll work with Elliot and Arlindo to see if the list should be expanded or the approach re-thought.    E.g., the list already does not include resolutions that we sometimes run (C12, C1440), though the former are not for science and the latter generally is without GOCART.

**Comment by mathomp4** [comment] 2021-02-05 17:30
@tclune This might be more prevalent in GEOS than you think. Moist has code that I'm always a bit iffy on:
```fortran
      if( imsize.le.200       ) call MAPL_GetResource(STATE, RASPARAMS%MAXDALLOWED_S, 'MAXDALLOWED_S:', DEFAULT= 4000.0 ,RC=STATUS)
      if( imsize.gt.200 .and. &
          imsize.le.400       ) call MAPL_GetResource(STATE, RASPARAMS%MAXDALLOWED_S, 'MAXDALLOWED_S:', DEFAULT= 2000.0 ,RC=STATUS)
      if( imsize.gt.400 .and. &
```
To me it seems like we should use things like `AREA` from FV3, say. Because, what if stretched grid? Then the "grid size" could be radically different in places.

**Comment by tclune** [comment] 2021-02-05 17:32
Actually I easily "believe" that the problem is common.    I've just been told not to allow that sort of things by senior staff on occasion.

**Comment by tclune** [comment] 2021-02-11 19:14
I've not forgotten about this issue.   Even managed a brief somewhat cryptic exchange with Arlindo about best approach.   My thinking is to move the resolution boundaries into the RC file.  Then one either needs to have a grid-type agnostic resolution parameter (e.g., DX along the equator) that is generated by MAPL for selecting the relevant case, _or_ have a separate block for each allowed grid type.    If we had YAML, the config file for the first approach  could look something like:
```yaml
Ch_DU:
  - {dx_min: 420., dx_max: 100000., value:    1.234}  # C90 
  - {dx_min: 400., dx_max: 420., value:    1.234}  # C96 
  - {dx_min: 200., dx_max: 400., value:  7.34} # C180
  - {dx_min: 100., dx_max: 200., value: 17.333} # C360
```  
The variant could look like:
```yaml
Ch_DU:
  cubed-sphere:
    C90:   1.23
    C180:  2.71
    C192: 3.14
  latlon:
    144x72:  1.23
    288x144: 2.71
```

The first method is friendlier to supporting intermediate resolutions without explicitly listing them.   The latter is much easier for the human to derive in the first place.    Similar structures for config files are less friendly, but could be defined once we have agreed upon an approach.

Thoughts?

**Comment by mathomp4** [comment] 2021-02-11 19:21
I will say that I think the first one is probably "better" in that it might support stretched grids in the future. Since you could have 10 km `DX` in one column and then 10000 km at its antipodal column, if the code only cared about `DX` (or `AREA`, whatever) for the current column, then you would still have the "right" value for that column.

**Comment by amolod** [comment] 2021-02-11 19:31
nathan did something about the other res-dependant parameter settings in the
model as he was using the periodic boundary conditions option in dycore, and
also for single column model. may be worth checking with him about what he did.

-------------------------------
Andrea M. Molod, Ph.D.
Global Modeling and Assimilation Office
NASA Goddard Space Flight Center
Desk: 301-614-6845
-------------------------------

**Comment by mathomp4** [comment] 2021-02-11 19:56
Pinging @narnold1 ... 😄

**Comment by narnold1** [comment] 2021-02-11 20:12
I did change the resolution-dependent parameters in Moist to vary smoothly with AREA, but the code was non-zero-diff, and there never seemed a good time to make it "official"...  I can revive that code to address this problem in Moist and Turb, but Tom's approach may be the easiest universal fix in the short term.

**Comment by narnold1** [comment] 2021-02-11 20:41
My old code was based on Icarus-1, and only exists now on CVS branch b_npa_dp3 (_does_ that exist?).  The idea was to associate the parameter values at the time with the median AREA for each resolution, and interpolate between them.  Examples below. Horizontal bars show the range of AREA for each grid.
![image](https://user-images.githubusercontent.com/53791641/107695365-79330d00-6c7e-11eb-923f-14249074263a.png)

**Comment by mathomp4** [comment] 2021-02-11 20:58
@narnold1 I do see the code on CVS, yes. Though it's possible we'd want a "generic" routine (in MAPL?) that does what you did. Load a yaml with parameters or something and apply the interpolator over the area points provided, etc.

**Comment by narnold1** [comment] 2021-02-12 15:17
@mathomp4 I like the idea of a generic routine to do this.

**Comment by tclune** [comment] 2021-02-12 15:46
I'll try to run this approach (grid-cell dependent parameter fill) past Arlindo and Anton for the GOCART use case.  I think it makes more sense than a global value that still depends on resolution.     But ... it is not zero diff, and there may be additional expense to carrying an array instead of a scalar.

**Comment by adarmenov** [comment] 2021-02-12 19:51
Agreed - (globally uniform) parameter interpolation based on grid-cell area would be the way to go in cases of (approximately) equal-area grids. Extending this approach for other type of grids and allowing for spatially varying parameter as a function of the grid-cell area, sound good, however I am concerned about how would one determine the tabulated values in practice.

Perhaps expressing this parameter as a product of two terms - 'grid ID' and 'area dependent', would cover most cases.  E.g., C = C_grid * C_area.  

C_grid = {'CS': 1.0, 'HHGG': 42}   # grid ID, value
C_area = ( (10^2, 1), (20^2, 2) , ...)  # resolution, value

**Comment by amdasilva** [comment] 2022-03-17 22:08
Moving this tio the SomeDayMaybe list.

**Closed by amdasilva** 2022-03-17 22:08 UTC
Labels: enhancement, SomeDayMaybe
